DROP TABLE "REVIEW_PHOTO";
DROP TABLE "REVIEW";
DROP TABLE "APPLY_CANCEL";
DROP TABLE "CLASS_APPLY";
DROP TABLE "CLASS_SCHEDULE";
DROP TABLE "CLASS_PHOTO";
DROP TABLE "CLASS_OPTION";
DROP TABLE "CLASS";
DROP TABLE "CATEGORY";
DROP TABLE "AREA";
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PWD"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(30)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(13)		NOT NULL,
	"MEMBER_IMG"	VARCHAR2(100)	DEFAULT './images/member/basic.jpg'	 NOT NULL
);
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);
COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '- 포함';
COMMENT ON COLUMN "MEMBER"."MEMBER_IMG" IS './images/member/파일이름';

CREATE TABLE "AREA" (
	"AREA_CODE"	NUMBER(2)		NOT NULL,
	"AREA_NAME"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "AREA" ADD CONSTRAINT "PK_AREA" PRIMARY KEY (
	"AREA_CODE"
);

CREATE TABLE "CATEGORY" (
	"CATEGORY_CODE"	NUMBER(2)		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(50)		NOT NULL
);
ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_CODE"
);

CREATE TABLE "CLASS" (
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CATEGORY_CODE"	NUMBER(2)		NOT NULL,
	"CLASS_NAME"	VARCHAR2(200)		NOT NULL,
	"CLASS_IMG"	VARCHAR2(100)		NOT NULL,
	"CLASS_INTRO"	VARCHAR2(4000)		NOT NULL,
	"CLASS_CUR"	VARCHAR2(3000)		NOT NULL,
	"CLASS_HOST"	VARCHAR2(2000)		NOT NULL,
	"CLASS_ALLTIME"	VARCHAR2(30)		NOT NULL,
	"CLASS_PRD"	VARCHAR2(600)		NULL,
	"CLASS_ATT"	VARCHAR2(600)		NULL,
	"AREA_CODE"	NUMBER(2)		NOT NULL,
	"CLASS_ADRESS"	VARCHAR2(300)		NOT NULL,
	"CLASS_PRICE"	NUMBER(10)		NOT NULL,
	"CLASS_LEVEL"	NUMBER(1)		NOT NULL,
	"CLASS_MIN"	NUMBER(2)		NOT NULL,
	"CLASS_MAX"	NUMBER(2)		NOT NULL
);
ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY (
	"CLASS_CODE"
);
COMMENT ON COLUMN "CLASS"."CLASS_IMG" IS './images/class/파일이름';
COMMENT ON COLUMN "CLASS"."CLASS_LEVEL" IS '1초급,2중급,3고급';

CREATE TABLE "CLASS_OPTION" (
	"CO_CODE"	NUMBER(2)		NOT NULL,
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CO_NAME"	VARCHAR2(100)		NOT NULL,
	"CO_PRICE"	NUMBER(10)		NOT NULL
);
ALTER TABLE "CLASS_OPTION" ADD CONSTRAINT "PK_CO" PRIMARY KEY (
	"CO_CODE"
);

CREATE TABLE "CLASS_PHOTO" (
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CP_ROUTE"	VARCHAR2(100)		NOT NULL,
	"CP_TYPE"	NUMBER(1)		NOT NULL
);
COMMENT ON COLUMN "CLASS_PHOTO"."CP_ROUTE" IS './images/class/파일이름';
COMMENT ON COLUMN "CLASS_PHOTO"."CP_TYPE" IS '0클래스 사진, 1클래스소개 첨부사진';

CREATE TABLE "CLASS_SCHEDULE" (
	"CS_CODE"	NUMBER		NOT NULL,
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CS_DAY"	NUMBER(5)		NOT NULL,
	"CS_STIME"	VARCHAR2(20)		NULL,
	"CS_FTIME"	VARCHAR2(20)		NULL,
	"CS_SDATE"	DATE		NOT NULL,
	"CS_FDATE"	DATE		NOT NULL
);
ALTER TABLE "CLASS_SCHEDULE" ADD CONSTRAINT "PK_CS" PRIMARY KEY (
	"CS_CODE",
	"CLASS_CODE"
);
COMMENT ON COLUMN "CLASS_SCHEDULE"."CS_DAY" IS '비트논리연산자로 요일체크';
COMMENT ON COLUMN "CLASS_SCHEDULE"."CS_SDATE" IS '2022-12-02';

CREATE TABLE "CLASS_APPLY" (
	"CA_CODE"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"CA_TOTAL"	NUMBER(2)		NOT NULL,
	"CA_TIME"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"CO_CODE"	NUMBER(2)		NULL,
	"CS_CODE"	NUMBER		NOT NULL,
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CA_CANCEL"	CHAR(1)	DEFAULT 'N' NOT NULL
);
ALTER TABLE "CLASS_APPLY" ADD CONSTRAINT "PK_CA" PRIMARY KEY (
	"CA_CODE"
);
COMMENT ON COLUMN "CLASS_APPLY"."CA_CANCEL" IS '정상진행N,취소Y';

CREATE TABLE "APPLY_CANCEL" (
	"AC_CODE"	NUMBER		NOT NULL,
	"AC_TIME"	TIMESTAMP   DEFAULT CURRENT_TIMESTAMP	NOT NULL
);
ALTER TABLE "APPLY_CANCEL" ADD CONSTRAINT "PK_AC" PRIMARY KEY (
	"AC_CODE"
);

CREATE TABLE "REVIEW" (
	"REVIEW_CODE"	NUMBER		NOT NULL,
	"CA_CODE"	NUMBER		NOT NULL,
	"REVIEW_TIME"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"REVIEW_CONT"	VARCHAR2(1000)		NOT NULL,
	"REVIEW_GRADE"	NUMBER(2,1)		NOT NULL,
	"REVIEW_KIND"	NUMBER(1)		NOT NULL,
	"REVIEW_COMPONENT"	NUMBER(1)		NOT NULL,
	"REVIEW_FACILITY"	NUMBER(1)		NOT NULL,
	"REVIEW_LEVEL"	NUMBER(1)		NOT NULL,
	"REVIEW_GROUP"	NUMBER(1)	DEFAULT 0	NOT NULL
);
ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_CODE"
);
COMMENT ON COLUMN "REVIEW"."REVIEW_GRADE" IS '4가지 평점 평균 소수 첫째 자리까지 반올림';
COMMENT ON COLUMN "REVIEW"."REVIEW_KIND" IS '0~5에 따라 불만족,만족';
COMMENT ON COLUMN "REVIEW"."REVIEW_COMPONENT" IS '0~5에 따라 불만족,만족';
COMMENT ON COLUMN "REVIEW"."REVIEW_FACILITY" IS '0~5에 따라 불만족,만족';
COMMENT ON COLUMN "REVIEW"."REVIEW_LEVEL" IS '0~5에 따라 적합,부적합';
COMMENT ON COLUMN "REVIEW"."REVIEW_GROUP" IS '미선택0,혼자1,친구2,연인3,가족4';

CREATE TABLE "REVIEW_PHOTO" (
	"REVIEW_CODE"	NUMBER		NOT NULL,
	"RP_ROUTE"	VARCHAR2(100)		NOT NULL
);
COMMENT ON COLUMN "REVIEW_PHOTO"."RP_ROUTE" IS './images/review/파일이름';

ALTER TABLE "CLASS" ADD CONSTRAINT "FK_CATEGORY_CLASS_1" FOREIGN KEY (
	"CATEGORY_CODE"
)
REFERENCES "CATEGORY" (
	"CATEGORY_CODE"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "FK_AREA_CLASS_1" FOREIGN KEY (
	"AREA_CODE"
)
REFERENCES "AREA" (
	"AREA_CODE"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_CA_REVIEW_1" FOREIGN KEY (
	"CA_CODE"
)
REFERENCES "CLASS_APPLY" (
	"CA_CODE"
);

ALTER TABLE "CLASS_APPLY" ADD CONSTRAINT "FK_MEMBER_CA_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "CLASS_APPLY" ADD CONSTRAINT "FK_CO_CA_1" FOREIGN KEY (
	"CO_CODE"
)
REFERENCES "CLASS_OPTION" (
	"CO_CODE"
);

ALTER TABLE "CLASS_APPLY" ADD CONSTRAINT "FK_CS_CA_1" FOREIGN KEY (
	"CS_CODE",
    "CLASS_CODE"
)
REFERENCES "CLASS_SCHEDULE" (
	"CS_CODE",
	"CLASS_CODE"
);

ALTER TABLE "CLASS_OPTION" ADD CONSTRAINT "FK_CLASS_CO_1" FOREIGN KEY (
	"CLASS_CODE"
)
REFERENCES "CLASS" (
	"CLASS_CODE"
);

ALTER TABLE "CLASS_SCHEDULE" ADD CONSTRAINT "FK_CLASS_CS_1" FOREIGN KEY (
	"CLASS_CODE"
)
REFERENCES "CLASS" (
	"CLASS_CODE"
);

ALTER TABLE "CLASS_PHOTO" ADD CONSTRAINT "FK_CLASS_CP_1" FOREIGN KEY (
	"CLASS_CODE"
)
REFERENCES "CLASS" (
	"CLASS_CODE"
);

ALTER TABLE "REVIEW_PHOTO" ADD CONSTRAINT "FK_REVIEW_RP_1" FOREIGN KEY (
	"REVIEW_CODE"
)
REFERENCES "REVIEW" (
	"REVIEW_CODE"
);

ALTER TABLE "APPLY_CANCEL" ADD CONSTRAINT "FK_CA_AC_1" FOREIGN KEY (
	"AC_CODE"
)
REFERENCES "CLASS_APPLY" (
	"CA_CODE"
);

